name: Run Tests and Coverage

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Set permissions
      run: chmod -R 755 *
      
    - name: npm install
      run: 
        npm install
        
    - name: install nyc globally
      run:
        npm i nyc -g
        
    - name: run tests
      run: 
        npm run test       

    - name: Coveralls
      uses: coverallsapp/github-action@main
      with:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}    
        
    - name: upload to Coveralls
      run: 
        nyc report --reporter=text-lcov | coveralls    
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}        
