name: Run Tests and Coverage

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - name: install dependencies
        run: npm ci 
      - name: Run tests
        run: npm run test || echo "Tests failed, but continuing..."
      - name: Create test report
        run: npx nyc report --reporter=lcov --reporter=text-lcov || echo "Failed to create test report, but continuing..."    
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}	
