name: Run Tests and Coverage

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: run tests 
        run: npm run mocha     
      - name: create test report
        run: nyc report --reporter=lcov --reporter=text-lcov      
