name: Run Tests and Coverage

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'    
      
    - name: npm install
      run: 
        npm install        
        
    - name: run tests
      run: 
        npm run test         

    - name: create report
      run: nyc report --reporter=lcov --reporter=text-lcov      
