name: Run Tests and Coverage

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: sw-test-app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Set permissions
      run: chmod -R 755 *
      
    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage
        
    - name: Coveralls
      uses: coverallsapp/github-action@v2

     
